# Generated by Django 4.2.1 on 2023-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('googleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_with_GPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('gpt_message', models.TextField()),
            ],
        ),
    ]
