# Generated by Django 4.2.1 on 2023-05-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPT_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Chat_with_GPT',
        ),
    ]
