# Generated by Django 4.2.1 on 2023-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleApp', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/default icon.png', upload_to='avatars/%y'),
        ),
    ]
