# Generated by Django 4.2.1 on 2023-05-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleApp', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(default='')),
                ('gpt_message', models.TextField(default='')),
                ('name', models.CharField(default='', editable=False, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat_GPT',
        ),
    ]
