# Generated by Django 4.2.1 on 2023-05-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleApp', '0009_chatgpthistory_delete_chat_gpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
