# Generated by Django 4.2.1 on 2024-04-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleApp', '0012_profilesearch_delete_profilesearche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileSearch',
        ),
    ]
